services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-desafioNode}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
